apiVersion: v1
kind: Service
metadata:
  name: superchat-react-app
  labels:
    app: superchat
    component: frontend
spec:
  type: ClusterIP
  selector:
    app: superchat
    component: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
